[package]
name = "scx_model"
version = "0.1.0"
edition = "2024"

[dependencies]
average = "0.16.0"
keyed_priority_queue = "0.4.2"
num-traits = "0.2.19"
rand = "0.9.2"
rand_distr = "0.5.1"

[lib]
path = "src/lib.rs"
name = "scx_model"
